# set the base image
FROM ubuntu

# set python image
FROM python:3

# make the working directory
RUN mkdir /analysis

# set the working directory
WORKDIR /analysis

# add python libraries
ADD requirements.txt /analysis/

# run the requirements.txt to pip install
RUN pip install -r requirements.txt

# add to working directory
ADD . /analysis/
